import { BookOpen, Gamepad2, Pencil, Library, Tag } from 'lucide-react'

export const CATEGORIAS_CONFIG = [
  {
    value: 'hq',
    label: 'Histórias em\nQuadrinhos',
    labelFlat: 'Histórias em Quadrinhos',
    descricao: 'HQs religiosas em PDF, prontas para baixar e compartilhar com a família.',
    icon: BookOpen,
    color: '#D4AF37',
    image: '/hq.png',
    gradient: 'from-[#D4AF37]/25 via-[#D4AF37]/10 to-transparent',
    border: 'border-[#D4AF37]/20 hover:border-[#D4AF37]/50',
    glow: 'rgba(212,175,55,0.4)',
  },
  {
    value: 'jogo',
    label: 'Jogos\nEducativos',
    labelFlat: 'Jogos Educativos',
    descricao: 'Atividades lúdicas e pedagógicas para crianças aprenderem brincando.',
    icon: Gamepad2,
    color: '#10b981',
    image: '/jogos.png',
    gradient: 'from-[#10b981]/25 via-[#10b981]/10 to-transparent',
    border: 'border-[#10b981]/20 hover:border-[#10b981]/50',
    glow: 'rgba(16,185,129,0.4)',
  },
  {
    value: 'desenho',
    label: 'Desenhos para\nColorir',
    labelFlat: 'Desenhos para Colorir',
    descricao: 'Ilustrações religiosas para imprimir e colorir, perfeitas para catequese.',
    icon: Pencil,
    color: '#818cf8',
    image: '/desenho.png',
    gradient: 'from-[#818cf8]/25 via-[#818cf8]/10 to-transparent',
    border: 'border-[#818cf8]/20 hover:border-[#818cf8]/50',
    glow: 'rgba(129,140,248,0.4)',
  },
  {
    value: 'livro',
    label: 'Livros\nDigitais',
    labelFlat: 'Livros Digitais',
    descricao: 'Leituras formativas e espirituais exclusivas em formato PDF.',
    icon: Library,
    color: '#f97316',
    image: '/livros.png',
    gradient: 'from-[#f97316]/25 via-[#f97316]/10 to-transparent',
    border: 'border-[#f97316]/20 hover:border-[#f97316]/50',
    glow: 'rgba(249,115,22,0.4)',
  },
  {
    value: 'adesivo',
    label: 'Adesivos\nCatequéticos',
    labelFlat: 'Adesivos Catequéticos',
    descricao: 'Adesivos e artes prontas para imprimir e decorar materiais catequéticos.',
    icon: Tag,
    color: '#ec4899',
    image: '/adesivos.png',
    gradient: 'from-[#ec4899]/25 via-[#ec4899]/10 to-transparent',
    border: 'border-[#ec4899]/20 hover:border-[#ec4899]/50',
    glow: 'rgba(236,72,153,0.4)',
  },
]
